# gcloud sdk for pubsub emulator with netcat added for the startup health check
FROM google/cloud-sdk:448.0.0@sha256:3025f5d021af63c36031730e7c77d5d577866effd9e9799a028f21d64a5fff64
RUN apt-get install -y netcat
