# gcloud sdk for pubsub emulator with netcat added for the startup health check
FROM google/cloud-sdk:450.0.0@sha256:6434fe45872bf3c3a0f2b5f5e389acbfe75f0556d68c79fe46b8d840f1a4c7f5
RUN apt-get install -y netcat
