# gcloud sdk for pubsub emulator with netcat added for the startup health check
FROM google/cloud-sdk:453.0.0@sha256:a5bcff5473f9d5cadcdd0e9f775d0e019ff258aece8709290173a434bf592868
RUN apt-get install -y netcat
